Repository 42Blank/ft_irc, pull requests merged in 2023-01, with the labels that each got.

#7 fix : 소켓으로 계속 메세지 받도록 했습니다.
  .DS_Store
  .gitignore
  Makefile
  includes/.DS_Store
  includes/Channel.hpp
  includes/Server.hpp
  src/.DS_Store
  src/Channel.cpp
  src/Server.cpp
  src/server.c
Labels: FEAT✨

#8 [Feat] Polling 방식으로 변경
  .gitignore
  Makefile
  includes/Error.hpp
  includes/Server.hpp
  includes/irc.hpp
  src/Command.cpp
  src/Error.cpp
  src/Server.cpp
  src/Verify.cpp
  src/utils.cpp
Labels: enhancement

#15 [Feat] 비밀번호 검증 추가, RFC 예외 추가, 예외처리 수정, CAP, PING, PONG 추가
  Makefile
  includes/Channel.hpp
  includes/Error.hpp
  includes/Reply.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/irc.hpp
  src/Channel.cpp
  src/Command.cpp
  src/CommandAuth.cpp
  src/CommandChannel.cpp
  src/Error.cpp
  src/Reply.cpp
  src/Server.cpp
  src/User.cpp
  src/main.cpp
  src/utils.cpp
Labels: enhancement

#35 [Feat] Quit 추가, channel 쪽 함수 고침, iter 문제 수정 등등
  Makefile
  includes/Reply.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/irc.hpp
  src/Channel.cpp
  src/Command.cpp
  src/CommandAuth.cpp
  src/CommandChannel.cpp
  src/Error.cpp
  src/Reply.cpp
  src/Server.cpp
  src/ServerSendMessage.cpp
  src/User.cpp
  src/utils.cpp
Labels: enhancement

#43 Fix/cmd quit
  includes/User.hpp
  src/Command.cpp
  src/CommandChannel.cpp
  src/User.cpp
Labels: bug

#62 feat: #56 file transfer - MSG 수정
  src/CommandChannel.cpp
Labels: FEAT✨
